// <auto-generated />
using System;
using HRDesk.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDesk.Web.Migrations
{
    [DbContext(typeof(BiometricAttendanceDbContext))]
    [Migration("20260705103918_AddWhatsAppGroupIdToOrganizations")]
    partial class AddWhatsAppGroupIdToOrganizations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HRDesk.Web.Models.ApplicationSequence", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnName("month");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int")
                        .HasColumnName("current_value");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Year", "Month");

                    b.HasIndex("OrganizationId");

                    b.ToTable("application_sequences");
                });

            modelBuilder.Entity("HRDesk.Web.Models.AttendanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int")
                        .HasColumnName("machine_number");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("PunchTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("punch_time");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.Property<int>("VerifyMode")
                        .HasColumnType("int")
                        .HasColumnName("verify_mode");

                    b.Property<string>("VerifyType")
                        .HasColumnType("longtext")
                        .HasColumnName("verify_type");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_employee_id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PunchTime")
                        .HasDatabaseName("idx_punch_time");

                    b.HasIndex("SyncedAt")
                        .HasDatabaseName("idx_synced_at");

                    b.ToTable("attendance_logs", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.AttendanceRegularization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("application_number");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_date");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("PunchTimeIn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("punch_time_in");

                    b.Property<DateTime?>("PunchTimeOut")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("punch_time_out");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date")
                        .HasColumnName("request_date");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("request_type");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<bool>("WaivePenalty")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("waive_penalty");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("attendance_regularizations");
                });

            modelBuilder.Entity("HRDesk.Web.Models.CompOffCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditedDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("credited_days");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("comp_off_credits");
                });

            modelBuilder.Entity("HRDesk.Web.Models.CompOffRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_date");

                    b.Property<decimal?>("CompOffDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("comp_off_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly?>("InTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("in_time");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<TimeOnly?>("OutTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("out_time");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("request_date");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WorkMinutes")
                        .HasColumnType("int")
                        .HasColumnName("work_minutes");

                    b.Property<DateOnly>("WorkedDate")
                        .HasColumnType("date")
                        .HasColumnName("worked_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftId");

                    b.ToTable("comp_off_requests");
                });

            modelBuilder.Entity("HRDesk.Web.Models.DailyAttendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("application_number");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("int")
                        .HasColumnName("break_minutes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EarlyMinutes")
                        .HasColumnType("int")
                        .HasColumnName("early_minutes");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly?>("InTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("in_time");

                    b.Property<bool>("IsActualBreak")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_actual_break");

                    b.Property<bool>("IsEarly")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_early");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_half_day");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("int")
                        .HasColumnName("late_minutes");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<TimeOnly?>("OutTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("out_time");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remarks");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkMinutes")
                        .HasColumnType("int")
                        .HasColumnName("work_minutes");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_daily_att_employee_id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RecordDate")
                        .HasDatabaseName("idx_daily_att_record_date");

                    b.HasIndex("ShiftId");

                    b.HasIndex("EmployeeId", "RecordDate")
                        .IsUnique()
                        .HasDatabaseName("idx_daily_att_emp_date");

                    b.ToTable("daily_attendance", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("department_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("designation_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("designations", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.DeviceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommKey")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("DeviceConfigurations");
                });

            modelBuilder.Entity("HRDesk.Web.Models.DeviceSyncState", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceIp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_ip");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_sync_status");

                    b.Property<DateTime>("LastSyncedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_synced_time");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("RecordsSynced")
                        .HasColumnType("int")
                        .HasColumnName("records_synced");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("DeviceId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("device_sync_state");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int")
                        .HasColumnName("designation_id");

                    b.Property<string>("DeviceSyncError")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("device_sync_error");

                    b.Property<sbyte>("DeviceSynced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((sbyte)0)
                        .HasColumnName("device_synced");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_name");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<DateOnly?>("LastWorkingDate")
                        .HasColumnType("date")
                        .HasColumnName("LastWorkingDate");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("ProbationEnd")
                        .HasColumnType("date")
                        .HasColumnName("probation_end");

                    b.Property<DateOnly?>("ProbationStart")
                        .HasColumnType("date")
                        .HasColumnName("probation_start");

                    b.Property<DateOnly?>("ResignationDate")
                        .HasColumnType("date")
                        .HasColumnName("resignation_date");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Weekoff")
                        .HasColumnType("longtext")
                        .HasColumnName("weekoff");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("application_number");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("ForeclosureRemark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("foreclosure_remark");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("installment_amount");

                    b.Property<int>("Installments")
                        .HasColumnType("int")
                        .HasColumnName("installments");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("loan_amount");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("int")
                        .HasColumnName("loan_type_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("remaining_amount");

                    b.Property<int>("RemainingInstallments")
                        .HasColumnType("int")
                        .HasColumnName("remaining_installments");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StartingPaidInstallments")
                        .HasColumnType("int")
                        .HasColumnName("starting_paid_installments");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LoanTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("employee_loans", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeSalaryStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int")
                        .HasColumnName("component_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("employee_salary_structure", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftId");

                    b.ToTable("employee_shift_assignments");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("holiday_name");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_global");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.HolidayEmployee", b =>
                {
                    b.Property<int>("HolidayId")
                        .HasColumnType("int")
                        .HasColumnName("holiday_id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasKey("HolidayId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("holiday_employees", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("opening_balance");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("TotalAllocated")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_allocated");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UsedCount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("used_count");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("leave_allocations", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("application_number");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("day_type");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IgnoreSandwichRule")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ignore_sandwich_rule");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_days");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("leave_applications", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCarryForward")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allow_carry_forward");

                    b.Property<bool>("ApplicableAfterProbation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("applicable_after_probation");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("background_color");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultYearlyQuota")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("default_yearly_quota");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_paid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("text_color");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("leave_types", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveTypeEligibility", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasKey("EmployeeId", "LeaveTypeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("leave_type_eligibility", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LoanInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<string>("DueMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("due_month");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<int>("LoanId")
                        .HasColumnType("int")
                        .HasColumnName("loan_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("paid_amount");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<int?>("PayrollId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("loan_installments", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("max_amount");

                    b.Property<int?>("MaxInstallments")
                        .HasColumnType("int")
                        .HasColumnName("max_installments");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("loan_types", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("WhatsAppGroupId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("whatsapp_group_id");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("HRDesk.Web.Models.PayrollDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int")
                        .HasColumnName("component_id");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("component_name");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("component_type");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int")
                        .HasColumnName("payroll_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PayrollId");

                    b.ToTable("payroll_details", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.PayrollMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("AbsentDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("absent_days");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("gross_salary");

                    b.Property<decimal>("HalfDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("half_days");

                    b.Property<decimal>("Holidays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("holidays");

                    b.Property<string>("LeaveBreakdown")
                        .HasColumnType("longtext")
                        .HasColumnName("leave_breakdown");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("month");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("net_salary");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("PaidLeaves")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("paid_leaves");

                    b.Property<decimal>("PayableDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("payable_days");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<decimal>("PresentDays")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("present_days");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_date");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalDays")
                        .HasColumnType("int")
                        .HasColumnName("total_days");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_deductions");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_earnings");

                    b.Property<decimal>("UnpaidLeaves")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("unpaid_leaves");

                    b.Property<decimal>("Weekoffs")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("weekoffs");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("payroll_master", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.SalaryComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("component_code");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("component_name");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("component_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("salary_components", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ColorCode")
                        .HasColumnType("longtext")
                        .HasColumnName("color_code");

                    b.Property<TimeOnly?>("EarlyGoAllowedTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("early_go_allowed_time");

                    b.Property<int?>("EarlyGoFrequencyPerMonth")
                        .HasColumnType("int")
                        .HasColumnName("early_go_frequency_per_month");

                    b.Property<int?>("EarlyLeaveGraceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("early_leave_grace_minutes");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly?>("HalfTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("half_time");

                    b.Property<int?>("LateComingAllowedCountPerMonth")
                        .HasColumnType("int")
                        .HasColumnName("late_coming_allowed_count_per_month");

                    b.Property<int?>("LateComingGraceMinutes")
                        .HasColumnType("int")
                        .HasColumnName("late_coming_grace_minutes");

                    b.Property<bool?>("LateComingHalfDayOnExceed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("late_coming_half_day_on_exceed");

                    b.Property<int>("LunchBreakDuration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("lunch_break_duration");

                    b.Property<TimeOnly?>("LunchBreakEnd")
                        .HasColumnType("time(6)")
                        .HasColumnName("lunch_break_end");

                    b.Property<TimeOnly?>("LunchBreakStart")
                        .HasColumnType("time(6)")
                        .HasColumnName("lunch_break_start");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_code");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("shift_name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("WorkingHours")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("working_hours");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.ShiftRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsWeekOff")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_week_off");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<DateOnly>("RosterDate")
                        .HasColumnType("date")
                        .HasColumnName("roster_date");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int")
                        .HasColumnName("shift_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ShiftId");

                    b.ToTable("shift_roster");
                });

            modelBuilder.Entity("HRDesk.Web.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("HRDesk.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HRDesk.Web.Models.ApplicationSequence", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.AttendanceLog", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.AttendanceRegularization", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.CompOffCredit", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.CompOffRequest", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HRDesk.Web.Models.DailyAttendance", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Department", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Designation", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.DeviceConfiguration", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.DeviceSyncState", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Employee", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRDesk.Web.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeLoan", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.LoanType", "LoanType")
                        .WithMany()
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LoanType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeSalaryStructure", b =>
                {
                    b.HasOne("HRDesk.Web.Models.SalaryComponent", "SalaryComponent")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("SalaryComponent");
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeShiftAssignment", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Holiday", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.HolidayEmployee", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Holiday", "Holiday")
                        .WithMany("EligibleEmployees")
                        .HasForeignKey("HolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Holiday");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveAllocation", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveApplication", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveType", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveTypeEligibility", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.LeaveType", "LeaveType")
                        .WithMany("EligibleEmployees")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LoanInstallment", b =>
                {
                    b.HasOne("HRDesk.Web.Models.EmployeeLoan", "EmployeeLoan")
                        .WithMany("LoanInstallments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeLoan");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LoanType", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.PayrollDetail", b =>
                {
                    b.HasOne("HRDesk.Web.Models.SalaryComponent", "SalaryComponent")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.PayrollMaster", "PayrollMaster")
                        .WithMany("PayrollDetails")
                        .HasForeignKey("PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PayrollMaster");

                    b.Navigation("SalaryComponent");
                });

            modelBuilder.Entity("HRDesk.Web.Models.PayrollMaster", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.SalaryComponent", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Shift", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.ShiftRoster", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRDesk.Web.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HRDesk.Web.Models.SystemSetting", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.User", b =>
                {
                    b.HasOne("HRDesk.Web.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HRDesk.Web.Models.EmployeeLoan", b =>
                {
                    b.Navigation("LoanInstallments");
                });

            modelBuilder.Entity("HRDesk.Web.Models.Holiday", b =>
                {
                    b.Navigation("EligibleEmployees");
                });

            modelBuilder.Entity("HRDesk.Web.Models.LeaveType", b =>
                {
                    b.Navigation("EligibleEmployees");
                });

            modelBuilder.Entity("HRDesk.Web.Models.PayrollMaster", b =>
                {
                    b.Navigation("PayrollDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
