using System.ComponentModel.DataAnnotations.Schema;

namespace HRDesk.Web.Models;

public sealed class Employee : IMustHaveTenant, IArchivable
{
    public int EmployeeId { get; set; }

    [Column("archived_at")]
    public DateTime? ArchivedAt { get; set; }

    [Column("archived_by")]
    [System.ComponentModel.DataAnnotations.StringLength(150)]
    public string? ArchivedBy { get; set; }

    /// <summary>
    /// Opaque, non-enumerable identifier used in URLs and API responses instead of the
    /// internal integer EmployeeId, so employee IDs cannot be guessed/incremented by a client.
    /// Distinct from VerificationId, which is a stable public QR/ID-card verification token.
    /// </summary>
    public Guid PublicId { get; set; } = Guid.NewGuid();

    public Guid VerificationId { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Persistent on-device face identity token generated by flutter_face_liveness (FaceNet TFLite).
    /// Format: "FID-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    /// Null until the employee completes their first face punch (enrollment).
    /// On subsequent punches the app sends this value and the backend verifies it matches
    /// before allowing the punch.
    /// </summary>
    [System.ComponentModel.DataAnnotations.StringLength(64)]
    public string? FaceId { get; set; }

    public string EmployeeName { get; set; } = "";

    public int? DepartmentId { get; set; }

    public int? DesignationId { get; set; }

    [Column("reporting_manager_id")]
    public int? ReportingManagerId { get; set; }

    public Employee? ReportingManager { get; set; }

    public string? Phone { get; set; }

    public DateOnly? JoiningDate { get; set; }
    
    public DateOnly? ResignationDate { get; set; }

    public DateOnly? LastWorkingDate { get; set; }

    public DateOnly? ProbationStart { get; set; }

    public DateOnly? ProbationEnd { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string? Weekoff { get; set; }

    public string? Status { get; set; }

    public Department? Department { get; set; }

    public Designation? Designation { get; set; }

    public string? PhotoPath { get; set; }

    [NotMapped]
    public byte[]? PhotoData { get; set; }
    
    [NotMapped]
    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? PhotoContentType { get; set; }

    [Column("device_synced")]
    public int DeviceSynced { get; set; } // 0 = not in machine, 1 = in machine

    [Column("device_sync_error")]
    public string? DeviceSyncError { get; set; }

    [Column("branch_id")]
    public int? BranchId { get; set; }

    public Branch? Branch { get; set; }

    [System.ComponentModel.DataAnnotations.Schema.Column("organization_id")]
    public int OrganizationId { get; set; }

    public Organization? Organization { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(50)]
    public string? EmploymentType { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(10)]
    public string? BloodGroup { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(20)]
    public string? Gender { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(50)]
    public string? AttendanceType { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(50)]
    public string? MaritalStatus { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? Nationality { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? WorkEmail { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? PersonalEmail { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(500)]
    public string? CurrentAddress { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(500)]
    public string? PermanentAddress { get; set; }

    public bool HasProbation { get; set; }

    public int? ProbationDays { get; set; }

    public int? ContractDurationMonths { get; set; }

    public DateTime? ContractEndDate { get; set; }

    // ── Bank Account Details ─────────────────────────────────────────────────
    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? BankName { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(30)]
    public string? BankAccountNumber { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(15)]
    public string? BankIfscCode { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? BankAccountHolderName { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(20)]
    public string? BankAccountType { get; set; } // Savings, Current

    // ── Statutory / Compliance ───────────────────────────────────────────────
    [System.ComponentModel.DataAnnotations.StringLength(10)]
    public string? PanNumber { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(12)]
    public string? AadhaarNumber { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(22)]
    public string? UanNumber { get; set; } // Universal Account Number (EPFO)

    [System.ComponentModel.DataAnnotations.StringLength(30)]
    public string? PfNumber { get; set; } // EPF member ID

    [System.ComponentModel.DataAnnotations.StringLength(20)]
    public string? EsiNumber { get; set; } // Employee State Insurance

    // ── Emergency Contact ────────────────────────────────────────────────────
    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? EmergencyContactName { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(50)]
    public string? EmergencyContactRelation { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(20)]
    public string? EmergencyContactPhone { get; set; }

    /// <summary>
    /// JSON array of emergency contacts: [{name, relation, phone}, ...]
    /// Supports multiple contacts. The single-field EmergencyContactName/Relation/Phone
    /// are kept for backward compatibility — new code should use this field.
    /// </summary>
    [System.ComponentModel.DataAnnotations.StringLength(2000)]
    public string? EmergencyContacts { get; set; }

    // ── Additional Identity ──────────────────────────────────────────────────
    [System.ComponentModel.DataAnnotations.StringLength(100)]
    public string? FatherOrSpouseName { get; set; }

    [System.ComponentModel.DataAnnotations.StringLength(30)]
    public string? PassportNumber { get; set; }

    public int? NoticePeriodDays { get; set; }

    // ── Payroll ──────────────────────────────────────────────────────────────
    /// <summary>
    /// The Pay Group this employee belongs to.
    /// Controls salary calculation basis (CalendarDays, Fixed26, PerDay, etc.),
    /// PF/ESI/PT applicability, and the default salary structure template.
    /// </summary>
    [Column("pay_group_id")]
    public int? PayGroupId { get; set; }

    public PayGroup? PayGroup { get; set; }
}
