using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using HRDesk.Web.Data;
using HRDesk.Web.Models;
using HRDesk.Web.Services;
using System.Collections.Generic;

namespace HRDesk.Web.Pages.Regularizations
{
    public class RegularizationRequestItem
    {
        public DateOnly RequestDate { get; set; }
        public string? PunchTarget { get; set; } // "in", "out", "both"
        public DateTime? PunchTimeIn { get; set; }
        public DateTime? PunchTimeOut { get; set; }
        public string? Reason { get; set; }
    }

    public class CreateModel : PageModel
    {
        private readonly BiometricAttendanceDbContext _context;
        private readonly HRDesk.Web.Services.IAttendanceProcessorService _processor;

        public CreateModel(BiometricAttendanceDbContext context, HRDesk.Web.Services.IAttendanceProcessorService processor)
        {
            _context = context;
            _processor = processor;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            ViewData["EmployeeId"] = new SelectList(_context.Employees.Where(e => e.Status == "active"), "EmployeeId", "EmployeeName");
            ViewData["NextAppNo"] = (string?)null;
            return Page();
        }

        public IActionResult OnGetNextAppNoAsync(DateOnly date)
        {
            return new JsonResult(new { nextAppNo = (string?)null });
        }

        public async Task<IActionResult> OnGetExistingPunchAsync(int employeeId, DateOnly date)
        {
            var existing = await _context.DailyAttendance
                .Where(d => d.EmployeeId == employeeId && d.RecordDate == date)
                .Select(d => new { 
                    inTime = d.InTime.HasValue ? d.InTime.Value.ToString("HH:mm") : null, 
                    outTime = d.OutTime.HasValue ? d.OutTime.Value.ToString("HH:mm") : null 
                })
                .FirstOrDefaultAsync();

            var roster = await _context.ShiftRosters
                .Include(r => r.Shift)
                .FirstOrDefaultAsync(r => r.EmployeeId == employeeId && r.RosterDate == date);

            return new JsonResult(new { 
                punch = existing ?? new { inTime = (string?)null, outTime = (string?)null },
                shift = roster?.Shift != null ? new { start = roster.Shift.StartTime.ToString("HH:mm"), end = roster.Shift.EndTime.ToString("HH:mm") } : null
            });
        }

        [BindProperty]
        public AttendanceRegularization Regularization { get; set; } = default!;

        [BindProperty]
        public bool AutoGenerate { get; set; } = true;

        [BindProperty]
        public List<RegularizationRequestItem> Requests { get; set; } = new();

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _context.AttendanceRegularizations == null || Regularization == null)
            {
                return Page();
            }

            if (Requests == null || !Requests.Any())
            {
                ModelState.AddModelError(string.Empty, "At least one date must be selected.");
                return Page();
            }

            string? autoGeneratedAppNo = null;

            var requestDates = new List<DateOnly>();
            var now = DateTime.Now;

            for (int i = 0; i < Requests.Count; i++)
            {
                var reqItem = Requests[i];
                var newReg = new AttendanceRegularization
                {
                    EmployeeId = Regularization.EmployeeId,
                    RequestType = Regularization.RequestType,
                    WaivePenalty = Regularization.WaivePenalty,
                    Reason = !string.IsNullOrWhiteSpace(reqItem.Reason) ? reqItem.Reason : Regularization.Reason,
                    RequestDate = reqItem.RequestDate,
                    CreatedAt = now,
                    Status = "Approved",
                    ApprovedBy = User.Identity?.Name ?? "Auto-Approved",
                    ApproveDate = now
                };

                if (newReg.RequestType == "Missed Punch")
                {
                    if (reqItem.PunchTarget == "both" || reqItem.PunchTarget == "out")
                    {
                        newReg.PunchTimeOut = reqItem.PunchTimeOut;
                        if (reqItem.PunchTarget == "out")
                        {
                            newReg.Reason += " (Out-Time Regularization)";
                        }
                        else
                        {
                            newReg.PunchTimeIn = reqItem.PunchTimeIn;
                            newReg.Reason += " (Full Day: IN & OUT)";
                        }
                    }
                    else if (reqItem.PunchTarget == "in")
                    {
                        newReg.PunchTimeIn = reqItem.PunchTimeIn;
                        newReg.Reason += " (In-Time Regularization)";
                    }
                }

                _context.AttendanceRegularizations.Add(newReg);
                requestDates.Add(newReg.RequestDate);
            }
            
            await _context.SaveChangesAsync();

            // PROCESS IMMEDIATELY IN BACKGROUND (Until end of month to update frequencies)
            var empId = Regularization.EmployeeId;
            var scopeFactory = HttpContext.RequestServices.GetRequiredService<IServiceScopeFactory>();
            
            _ = Task.Run(async () =>
            {
                try
                {
                    using var scope = scopeFactory.CreateScope();
                    var processor = scope.ServiceProvider.GetRequiredService<IAttendanceProcessorService>();
                    
                    var datesToProcess = new HashSet<DateOnly>();
                    foreach (var rDate in requestDates.Distinct())
                    {
                        var endOfMonth = new DateOnly(rDate.Year, rDate.Month, DateTime.DaysInMonth(rDate.Year, rDate.Month));
                        for (var d = rDate; d <= endOfMonth; d = d.AddDays(1))
                        {
                            datesToProcess.Add(d);
                        }
                    }

                    foreach (var d in datesToProcess.OrderBy(x => x))
                    {
                        await processor.ProcessDailyAttendanceAsync(d, empId);
                    }
                }
                catch
                {
                    // Ignore background processing errors
                }
            });

            return RedirectToPage("./Index");
        }
    }
}
